services:
  - type: web
    name: mpp-frontend
    env: node
    region: oregon  # Match with backend region
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://mpp-backend-1-f82n.onrender.com
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health  # Next.js API route for health check
    autoDeploy: true
    staticPublishPath: .next 